/**
 * Executable schema generated by Grats (https://grats.capt.dev)
 * Do not manually edit. Regenerate by running `npx grats`.
 */
import MyUserClass from "./src/for-grats/models/MyUser";
import queryAllUsersResolver from "./src/for-grats/models/MyUser";
import queryMeResolver from "./src/for-grats/models/MyUser";
import { myGreeting as queryMyGreetingResolver, person as queryPersonResolver } from "./src/for-grats/Query";
import { GraphQLSchema, GraphQLObjectType, GraphQLNonNull, GraphQLList, GraphQLString, GraphQLInterfaceType } from "graphql";
export function getSchema(): GraphQLSchema {
    const GroupType: GraphQLObjectType = new GraphQLObjectType({
        name: "Group",
        fields() {
            return {
                description: {
                    name: "description",
                    type: new GraphQLNonNull(GraphQLString)
                },
                name: {
                    name: "name",
                    type: new GraphQLNonNull(GraphQLString)
                }
            };
        }
    });
    const IPersonType: GraphQLInterfaceType = new GraphQLInterfaceType({
        name: "IPerson",
        fields() {
            return {
                name: {
                    name: "name",
                    type: new GraphQLNonNull(GraphQLString)
                }
            };
        },
        resolveType
    });
    const MyUserType: GraphQLObjectType = new GraphQLObjectType({
        name: "MyUser",
        fields() {
            return {
                groups: {
                    name: "groups",
                    type: new GraphQLNonNull(new GraphQLList(new GraphQLNonNull(GroupType)))
                },
                name: {
                    name: "name",
                    type: new GraphQLNonNull(GraphQLString)
                }
            };
        },
        interfaces() {
            return [IPersonType];
        }
    });
    const QueryType: GraphQLObjectType = new GraphQLObjectType({
        name: "Query",
        fields() {
            return {
                allUsers: {
                    name: "allUsers",
                    type: new GraphQLNonNull(new GraphQLList(new GraphQLNonNull(MyUserType))),
                    resolve() {
                        return queryAllUsersResolver.allUsers();
                    }
                },
                me: {
                    name: "me",
                    type: new GraphQLNonNull(MyUserType),
                    resolve() {
                        return queryMeResolver.me();
                    }
                },
                myGreeting: {
                    name: "myGreeting",
                    type: new GraphQLNonNull(GraphQLString),
                    resolve() {
                        return queryMyGreetingResolver();
                    }
                },
                person: {
                    name: "person",
                    type: new GraphQLNonNull(IPersonType),
                    resolve() {
                        return queryPersonResolver();
                    }
                }
            };
        }
    });
    return new GraphQLSchema({
        query: QueryType,
        types: [IPersonType, GroupType, MyUserType, QueryType]
    });
}
const typeNameMap = new Map();
typeNameMap.set(MyUserClass, "MyUser");
function resolveType(obj: any): string {
    if (typeof obj.__typename === "string") {
        return obj.__typename;
    }
    let prototype = Object.getPrototypeOf(obj);
    while (prototype) {
        const name = typeNameMap.get(prototype.constructor);
        if (name != null) {
            return name;
        }
        prototype = Object.getPrototypeOf(prototype);
    }
    throw new Error("Cannot find type name.");
}
